### ISSUE TITLE
db_schema

### ISSUE THREAD

**Issue by juliends** [CaroleConscients/groot#2]
Here is the schema:
![groot_schema](https://cloud.githubusercontent.com/assets/11377783/23942281/08bfe878-096c-11e7-8509-efa9d3953db3.png)

[groot_schema.txt](https://github.com/CaroleConscients/groot/files/843983/groot_schema.txt)

**Comment by CaroleConscients** [comment]
add tree_id to cards

**Comment by juliends** [comment]
Update of the schema with:
User:
  - Admin => will allow access to the sidekiq dashboard (checking emails enqueued) 
  - Congratulation => Boolean that triggers the congrats modal

Cards:
  - Tree Id => Counter for the 1000s user
